openapi: "3.0.0"
info:
  title: "API"
  version: "1.0.0"

servers:
  - url: "http://localhost:3002"
    description: "Mock server"
  - url: "http://localhost:1337"
    description: "Local server"

paths:
  /api/app-users:
    $ref: "./paths/users.yml"
  /api/app-users/{id}:
    $ref: "./paths/user.yml"

components:
  $ref: "./components.yml"