version: '3'

services:
  proxy:
    image: nginx:alpine
    container_name: piyomiru-proxy
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1234:80
    depends_on:
      - app
      - api

  app:
    build: .
    container_name: bff-app
    volumes:
      - ./:/go/src/app

  api:
    image: node:16-alpine
    container_name: api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - 1337:1337
    command: >
      sh -c "
        yarn &&
        yarn develop
      "

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "3000:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "3001:8080"
    volumes:
      - ./mock:/mock
    environment:
      SWAGGER_JSON: /mock/openapi.yml

  swagger-api:
    image: stoplight/prism:4
    container_name: "swagger-api"
    ports:
      - "3002:4010"
    command: mock -h 0.0.0.0 /mock/openapi.yml -d
    volumes:
      - ./mock:/mock